apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-ratings
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student84/ratings
maintainers:
  - name: student84
    email: devop084@mail.kmutt.ac.th
sources:
  - https://github.com/warisara-khruajinli/bookinfo-ratings