name: dev-env
on:
  push:
    branches:
      - dev
jobs:
  deploy-dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/warisara-khruajinli/bookinfo_ratings:dev

      - run: docker build -t ghcr.io/warisara-khruajinli/bookinfo-ratings:dev .
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker push ghcr.io/warisara-khruajinli/bookinfo-ratings:dev